### ISSUE TITLE
voting error with version v1.3.0

### ISSUE THREAD

**Issue by litaochen** [terra-project/oracle-feeder#21]
I switched to Terra core v0.4.5 and feeder v1.3.0 but see this error on feeder's voting:
"""
broadcast error: code: 13, raw_log: insufficient fee: insufficient fees; got: "", required: "190000uaud,190000ucad,140000uchf,980000ucny,..."(gas) +""(stability)
"""
Any idea why?

Terra Core  version:
name: terra
server_name: terrad
client_name: terracli
version: 0.4.5
commit: 534de88dbac0519f6f852ed411905b71a6c42e4e
build_tags: netgo,ledger
go: go version go1.13.3 linux/amd64

any idea why is this happening?

**Comment by hanjukim** [comment]
If you have --gas-prices parameter in your feeder command line, set the value to `169.77ukrw`

**Comment by hanjukim** [comment]
Oh and please upgrade it to the latest version (1.3.4 at the moment)

**Comment by litaochen** [comment]
Tried the latest version v1.3.4 (it is the laster mater branch per the commit hash)and see this error:
```
broadcast error: txhash not found: 8633CCA6DD70802F9BE59A1D0101527E5A5D6FD9E074A5C34CB26B2EBAFF12C8
```

Here is the feeder start command:
```
npm start vote -- \
   --source http://localhost:8532/latest \
   --lcd https://lcd.terra.dev \
   --chain-id columbus-4 \
   --denoms sdr,krw,usd,mnt,eur,cny,jpy,gbp,inr,cad,chf,hkd,aud,sgd,thb \
   --validator terravaloper12mcn4pj7d8yeff0xfedcthqe9gs3vwc2tn8sy2 \
   --password "***********" \
   --gas-prices 169.77ukrw
```

Running the lower version v1.2.0 works fine but that feeder burns krw very quickly, like 28 ukrw for every vote. Not sustainable.
Do you see issues in the feeder running command?

**Comment by Lucas-L** [comment]
Hello i'm having the same issues. 1.2.x is burning an insane amount of KRW and 1.3.4 outputs `broadcast error: txhash`  (I'm running lcd locally)

**Comment by litaochen** [comment]
@Lucas-L Thanks a lot! it worked with your method.
