### ISSUE TITLE
Oracle Feeder Request Non Existing LCD Endpoint

### ISSUE THREAD

**Issue by gaia** [terra-project/oracle-feeder#4]
running the current version of the feeder

`yarn start vote --source "http://price.terra.money/latest" --lcd http://localhost:1317  --chain-id columbus-3 --denoms krw,usd,sdr`

hitting the LCD

`terracli rest-server --chain-id=columbus-3 --laddr=tcp://localhost:1317 --node tcp://localhost:27657 --trust-node=true` (true because the RPC endpoint is a full node)

I get an error on the feeder side because it requests `http://localhost:1317/oracle/params` which does not exist. According to the [docs the correct endpoint](https://swagger.terra.money/#/Oracle/get_oracle_parameters) is `http://localhost:1317/oracle/parameters`

```
I[2020-01-09|23:45:25.735] Served RPC HTTP response                     module=rest-server method=GET url=/oracle/params status=404 duration=0 remoteAddr=127.0.0.1:43188
I[2020-01-09|23:45:25.738] Served RPC HTTP response                     module=rest-server method=GET url=/auth/accounts/terra1____________ status=200 duration=2 remoteAddr=127.0.0.1:43190
```

```
terra@node:~/scripts/oracle-feeder/feeder$ curl http://localhost:1317/oracle/params
404 page not found
terra@node1:~/scripts/oracle-feeder/feeder$ curl http://localhost:1317/oracle/parameters
{"height":"364926","result":{
  "vote_period": "5",
  "vote_threshold": "0.500000000000000000",
  "reward_band": "0.070000000000000000",
  "reward_distribution_window": "5256000",
  "whitelist": [
    "ukrw",
    "usdr",
    "uusd",
    "umnt"
  ],
  "slash_fraction": "0.000100000000000000",
  "slash_window": "432000",
  "min_valid_per_window": "0.050000000000000000"
```

**Comment by dokwon** [comment]
Try to use other oracle feeders, our reference solution sucks at the moment

**Comment by gaia** [comment]
updating https://github.com/terra-project/oracle-feeder/blob/d12e465168cecd38eb9a33a736d50d70c2659aa2/feeder/src/index.ts#L142 from params to parameters works, but it goes in a loop because it doesn't find a price feed. is there an available price feed i can plug into the reference tool?
